version: "3.8"
services:
  api:
    container_name: api
    restart: on-failure
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      NODE_ENV: development
      PORT: 4000
    ports:
      - "5000:4000"
    command: yarn start
    volumes:
      - .:/app/
      - /app/node_modules
  db:
    container_name: pg_container
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_USER}
      POSTGRES_PASSWORD: ${DOCKER_PASS}
      POSTGRES_DB: ${DOCKER_DB}
    ports:
      - '5434:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: {}
    # driver: local